### ISSUE TITLE
Clicking on magicLink -> Client side warning

### ISSUE THREAD

**Issue by jeremyisatrecharm** [supabase-community/auth-ui#49]
# Bug report
I _think_ it still works but gives the following warning:

```
next-dev.js?3515:20 Warning: Received `false` for a non-boolean attribute `loading`.

If you want to write it to the DOM, pass a string instead: loading="false" or loading={value.toString()}.

If you used to conditionally omit it with loading={condition && value}, pass loading={condition ? value : undefined} instead.
    at button
    at Button (webpack-internal:///./node_modules/@supabase/auth-ui-react/dist/esm/src/components/UI/Button.js:57:5)
    at div
    at Container (webpack-internal:///./node_modules/@supabase/auth-ui-react/dist/esm/src/components/UI/Container.js:47:5)
    at div
    at Container (webpack-internal:///./node_modules/@supabase/auth-ui-react/dist/esm/src/components/UI/Container.js:47:5)
    at form
    at MagicLink (webpack-internal:///./node_modules/@supabase/auth-ui-react/dist/esm/src/components/Auth/interfaces/MagicLink.js:31:5)
```

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Code:
```
    <Auth supabaseClient={supabaseClient} appearance={{ theme: ThemeSupa }} magicLink={true} />
```
Just click on "send a magic link email" with chrome dev tools open and you should see this error.

I am using the latest version of Next.js and React.

1. Go to '…'
2. Click on '…'
3. Scroll down to '…'

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Version of supabase-js: [e.g. 6.0.2]
- Version of Node.js: [e.g. 10.10.0]

**Comment by silentworks** [comment]
This is a warning, not a bug. Please upgrade to the latest version of the library `0.2.3` which should fix this warning.
